version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend
  - source: infrastructure/backend.conf
    destination: /etc/nginx/sites-available/
permissions:
  - object: /var/www/backend
    pattern: "**"
    owner: ec2-user
    group: www
hooks:
  BeforeInstall:
    - location: infrastructure/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: infrastructure/scripts/set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: infrastructure/scripts/post_install.sh
      timeout: 300
      runas: root
